language: php

sudo: required

php:
- 7.0
- 7.1
- 7.2
- nightly

matrix:
  allow_failures:
  - php: nightly

before_install:
- composer self-update

install:
- composer install --no-interaction

script:
- vendor/bin/phpcs
- vendor/bin/phpunit