#!/bin/bash
## Description: Set up the development environment
## Usage: orchestrate
## Example: "ddev orchestrate"

mkdir -p "${DDEV_DOCROOT}"
pushd "${DDEV_DOCROOT}"
MUPLUGIN_FOLDER="${DDEV_DOCROOT}/wp-content/mu-plugins/${PLUGIN_NAME:-$DDEV_PROJECT}"
TEST_PLUGIN_FOLDER="${DDEV_DOCROOT}/wp-content/plugins/wp-stash-test-plugin"
VALID_ARGS=$(getopt -o fp: --long force,plugin: -- "$@")
if [[ $? -ne 0 ]]; then
    exit 1;
fi

eval set -- "$VALID_ARGS"
while [ : ]; do
  case "$1" in
    -f | --force)
        echo "Removing WordPress installation"
        shift
        export RECREATE_ENV=1;
        popd
        find "${DDEV_DOCROOT}" -mindepth 1 ! -regex "^${MUPLUGIN_FOLDER}\(/.*\)?" ! -regex "^${TEST_PLUGIN_FOLDER}\(/.*\)?" -delete
        pushd "${DDEV_DOCROOT}"
        ;;
    --) shift;
        break
        ;;
  esac
done

# Execute all fragments from orchestrate.d
if [ -d "${0}.d" ]; then
    for FN in ${0}.d/*.sh ; do
      echo $FN
      source "${FN}"
    done
fi
