name: Run Playwright tests via wp-env
on:
    push:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    e2e-playwright:
        name: Run Playwright E2E tests
        uses: inpsyde/reusable-workflows/.github/workflows/test-playwright.yml@main
        with:
            NODE_VERSION: '22'
            NPM_REGISTRY_DOMAIN: https://registry.npmjs.org/
            PLAYWRIGHT_BROWSER_ARGS: firefox
            PRE_SCRIPT: npm run test:e2e:setup
            PLAYWRIGHT_SCRIPT: test:e2e
            PLAYWRIGHT_ARTIFACT_PATH: |
                tests/Playwright/playwright-report/
                tests/Playwright/test-results/
